import Head from 'next/head';
import { green, red, blue } from '@mui/material/colors';
import { Heading, ThemeProvider } from 'heading';
import { Button } from 'button';
import { Table } from 'table';
import { Link } from '@mui/material';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ThemeProvider
          theme={{
            palette: {
              primary: { main: blue[500] },
              info: { main: green[500] },
            },
            components: {
              heading: {
                styleOverrides: {
                  color: red[500],
                  border: '10px dotted skyblue',
                },
              },
            },
          }}
        >
          <Heading>
            Welcome to <Link href="https://nextjs.org">Next.js!</Link>
          </Heading>
        </ThemeProvider>
        <Button
          onClick={() => {
            console.log('clicked button');
          }}
          color="success"
        >
          Click Me
        </Button>
        <Table
          data={{
            headers: ['column 1', 'column 2'],
            rows: [
              ['foo', 'bar'],
              ['foo2', 'bar2'],
            ],
          }}
        />
      </main>
    </div>
  );
}
