import Head from 'next/head';
import { Heading } from 'heading';
import { Button } from 'button';
import { Table } from 'table';
import { Box, Button as MuiButton } from '@mui/material';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Heading>
        <Button
          onClick={() => {
            console.log('clicked button');
          }}
        >
          Click Me
        </Button>
        <Box m={1}>
          <MuiButton variant="contained" color="primary">
            Material UI 4 Button
          </MuiButton>
        </Box>
        <Table
          data={{
            headers: ['column 1', 'column 2'],
            rows: [
              ['foo', 'bar'],
              ['foo2', 'bar2'],
            ],
          }}
        />
        <p>App Content</p>
      </main>
    </div>
  );
}
