import Head from 'next/head';
import { Heading } from 'heading';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Heading>
        <button
          onClick={() => {
            console.log('clicked button');
          }}
        >
          Click Me
        </button>
      </main>
    </div>
  );
}
